name: Deploy backend to EC2

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/trexo-nodejs-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/trexo-nodejs-app:latest

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted

    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/trexo-nodejs-app:latest

      - name: Delete old container if exists
        run: docker rm -f node-js-app-container || true

      - name: Run Docker Container
        run: docker run -d --name node-js-app-container -p 4000:4000 -e MONGO_DB_PASSWORD='${{secrets.MONGO_DB_PASSWORD}}' ${{ secrets.DOCKER_USERNAME }}/trexo-nodejs-app:latest
